baseURL = 'https://vamsee.in/'
languageCode = 'en-us'
title = "Vamsee's Dev Blog"
theme = "cactus"
copyright = "Vamsee Kanakala"

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Writings"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[params]

  colortheme = "dark" # dark, light, white, or classic

  # Home page settings
  description = "Hi. My name is Vamsee Kanakala, and I mostly write about programming languages, technical leadership and other related topics. You can subscribe to my feed if you're interested."
