baseURL = 'https://vamsee.in/'
languageCode = 'en-us'
title = "Vamsee Kanakala"
theme = "cactus"
copyright = "Vamsee Kanakala"

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "dracula"
    tabWidth = 4

[params]

  colortheme = "dark" # dark, light, white, or classic
  rss = true

  # Home page settings
  description = "Hi. I'm a web developer turned devops engineer. I occasionally dabble in startups and engineering management as well. I mostly write about programming languages, technical leadership and other related topics here."
  mainSection = "posts" # your main section
  mainSectionTitle = "Posts"
  showAllPostsOnHomePage = false # default
  postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = false # show tags overview by default.
  showProjectsList = true # show projects list by default (if projects data file exists).
  projectsUrl = "https://github.com/vamsee" # title link for projects list

  [params.comments]
    enabled = false # default
    engine = "utterances" # only disqus, utterances, and cactus_comments is supported
    [params.comments.utterances]
      repo = "vamsee/vamsee.in"
      label = "vamsee.in" # you can use however you want to label your name in your repo's issues
      theme = "github-dark"

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "github"
    link = "https://github.com/vamsee"
  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/vamsee-kanakala"
  [[params.social]]
    name = "twitter"
    link = "https://twitter.com/vamsee"  # no need for "mailto:" in the head

[deployment]
  [[deployment.targets]]
  # An arbitrary name for this target.
  name = "s3"
  URL = "s3://vamsee.in?region=us-east-1"
